# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
jobs:
  include:
    language: generic
    addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.1,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
    script: travis/script.sh
