#!/bin/bash

rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
# remove files that are regenerated by 'cabal update'
rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
